export const users = [
  {
    key: "1",
    id: "1",
    date: "10-20-24",
    name: "Tony Reichert",
    gender: "male",
    yl: "2nd year",
    course: "Bachelor of Science in Secondary Education Major in Science",
    purpose: "pa aircon",
    ti: "10:30:00 AM",
    to: "1:30:00 PM",
  },
  {
    key: "2",
    id: "2",
    date: "10-21-24",
    name: "Sarah Walker",
    gender: "female",
    yl: "1st year",
    course: "BSED",
    purpose: "pa print",
    ti: "11:00:00 AM",
    to: "2:00:00 PM",
  },
  {
    key: "3",
    id: "3",
    date: "10-22-24",
    name: "Michael Chang",
    gender: "male",
    yl: "3rd year",
    course: "BSIT",
    purpose: "pa photocopy",
    ti: "12:00:00 PM",
    to: "3:00:00 PM",
  },
  {
    key: "4",
    id: "4",
    date: "10-23-24",
    name: "Emily Davis",
    gender: "female",
    yl: "4th year",
    course: "BSBA",
    purpose: "research",
    ti: "1:00:00 PM",
    to: "4:00:00 PM",
  },
  {
    key: "5",
    id: "5",
    date: "10-24-24",
    name: "Chris Kim",
    gender: "male",
    yl: "2nd year",
    course: "BEED",
    purpose: "library",
    ti: "9:00:00 AM",
    to: "12:00:00 PM",
  },
  {
    key: "6",
    id: "6",
    date: "10-25-24",
    name: "Jessica Lee",
    gender: "female",
    yl: "1st year",
    course: "BSBA",
    purpose: "project work",
    ti: "10:15:00 AM",
    to: "1:15:00 PM",
  },
  {
    key: "7",
    id: "7",
    date: "10-26-24",
    name: "Ethan Brown",
    gender: "male",
    yl: "3rd year",
    course: "BSCS",
    purpose: "computer lab",
    ti: "2:30:00 PM",
    to: "5:30:00 PM",
  },
  {
    key: "8",
    id: "8",
    date: "10-27-24",
    name: "Sophia Martinez",
    gender: "female",
    yl: "4th year",
    course: "BSED",
    purpose: "thesis research",
    ti: "8:45:00 AM",
    to: "11:45:00 AM",
  },
  {
    key: "9",
    id: "9",
    date: "10-28-24",
    name: "David Garcia",
    gender: "male",
    yl: "2nd year",
    course: "BSCS",
    purpose: "group study",
    ti: "1:00:00 PM",
    to: "4:00:00 PM",
  },
  {
    key: "10",
    id: "10",
    date: "10-29-24",
    name: "Emma Johnson",
    gender: "female",
    yl: "1st year",
    course: "BSIT",
    purpose: "borrow equipment",
    ti: "9:30:00 AM",
    to: "12:30:00 PM",
  },
  {
    key: "11",
    id: "11",
    date: "10-30-24",
    name: "Liam Wilson",
    gender: "male",
    yl: "3rd year",
    course: "BSBA",
    purpose: "consultation",
    ti: "11:00:00 AM",
    to: "2:00:00 PM",
  },
  {
    key: "12",
    id: "12",
    date: "10-31-24",
    name: "Ava Clark",
    gender: "female",
    yl: "4th year",
    course: "BSN",
    purpose: "lab work",
    ti: "12:30:00 PM",
    to: "3:30:00 PM",
  },
  {
    key: "13",
    id: "13",
    date: "11-01-24",
    name: "Noah Wright",
    gender: "male",
    yl: "2nd year",
    course: "BSME",
    purpose: "borrow book",
    ti: "10:00:00 AM",
    to: "1:00:00 PM",
  },
  {
    key: "14",
    id: "14",
    date: "11-02-24",
    name: "Olivia Adams",
    gender: "female",
    yl: "1st year",
    course: "BSA",
    purpose: "study",
    ti: "1:15:00 PM",
    to: "4:15:00 PM",
  },
  {
    key: "15",
    id: "15",
    date: "11-03-24",
    name: "James Carter",
    gender: "male",
    yl: "3rd year",
    course: "BSBIO",
    purpose: "online class",
    ti: "9:00:00 AM",
    to: "12:00:00 PM",
  },
  {
    key: "16",
    id: "16",
    date: "11-04-24",
    name: "Isabella Evans",
    gender: "female",
    yl: "2nd year",
    course: "BSTM",
    purpose: "meeting",
    ti: "3:00:00 PM",
    to: "6:00:00 PM",
  },
  {
    key: "17",
    id: "17",
    date: "11-05-24",
    name: "Benjamin Torres",
    gender: "male",
    yl: "4th year",
    course: "BSCE",
    purpose: "research",
    ti: "10:45:00 AM",
    to: "1:45:00 PM",
  },
  {
    key: "18",
    id: "18",
    date: "11-06-24",
    name: "Mia Gonzalez",
    gender: "female",
    yl: "1st year",
    course: "BSTM",
    purpose: "project discussion",
    ti: "2:00:00 PM",
    to: "5:00:00 PM",
  },
  {
    key: "19",
    id: "19",
    date: "11-07-24",
    name: "Daniel Ramirez",
    gender: "male",
    yl: "2nd year",
    course: "BSME",
    purpose: "study group",
    ti: "11:15:00 AM",
    to: "2:15:00 PM",
  },
  {
    key: "20",
    id: "20",
    date: "11-08-24",
    name: "Sophia Rodriguez",
    gender: "female",
    yl: "3rd year",
    course: "Bachelor of Science in Agriculture",
    purpose: "thesis prep",
    ti: "1:30:00 PM",
    to: "4:30:00 PM",
  },

  {
    key: "21",
    id: "21",
    date: "11-09-24",
    name: "Lucas Bennett",
    gender: "male",
    yl: "4th year",
    course: "Bachelor of Science in Agriculture",
    purpose: "library research",
    ti: "10:00:00 AM",
    to: "1:00:00 PM",
  },
  {
    key: "22",
    id: "22",
    date: "11-10-24",
    name: "Mason Turner",
    gender: "male",
    yl: "1st year",
    course: "Bachelor of Science in Agriculture",
    purpose: "borrow laptop",
    ti: "11:30:00 AM",
    to: "2:30:00 PM",
  },
  {
    key: "23",
    id: "23",
    date: "11-11-24",
    name: "Ella Mitchell",
    gender: "female",
    yl: "2nd year",
    course: "Bachelor of Science in Agriculture",
    purpose: "study session",
    ti: "9:00:00 AM",
    to: "12:00:00 PM",
  },
  {
    key: "24",
    id: "24",
    date: "11-12-24",
    name: "Henry Perez",
    gender: "male",
    yl: "3rd year",
    course: "Bachelor of Science in Agriculture",
    purpose: "computer lab",
    ti: "2:00:00 PM",
    to: "5:00:00 PM",
  },
  {
    key: "25",
    id: "25",
    date: "11-13-24",
    name: "Amelia Kelly",
    gender: "female",
    yl: "4th year",
    course: "Bachelor of Science in Agriculture",
    purpose: "project work",
    ti: "10:15:00 AM",
    to: "1:15:00 PM",
  },
  {
    key: "26",
    id: "26",
    date: "11-14-24",
    name: "Alexander Cruz",
    gender: "male",
    yl: "2nd year",
    course: "Bachelor of Science in Agriculture",
    purpose: "group meeting",
    ti: "12:00:00 PM",
    to: "3:00:00 PM",
  },
  {
    key: "27",
    id: "27",
    date: "11-15-24",
    name: "Avery Rivera",
    gender: "female",
    yl: "1st year",
    course: "BSIT major in Electronics",
    purpose: "presentation prep",
    ti: "9:45:00 AM",
    to: "12:45:00 PM",
  },
  {
    key: "28",
    id: "28",
    date: "11-16-24",
    name: "Samuel Morgan",
    gender: "male",
    yl: "3rd year",
    course: "Bachelor of Science in Secondary Education major in English",
    purpose: "research",
    ti: "10:30:00 AM",
    to: "1:30:00 PM",
  },
  {
    key: "29",
    id: "29",
    date: "11-17-24",
    name: "Lily James",
    gender: "female",
    yl: "4th year",
    course: "Bachelor of Science in Secondary Education major in English",
    purpose: "borrow equipment",
    ti: "1:00:00 PM",
    to: "4:00:00 PM",
  },
  {
    key: "30",
    id: "30",
    date: "11-18-24",
    name: "Jack Martinez",
    gender: "male",
    yl: "2nd year",
    course: "Bachelor of Science in Secondary Education major in English",
    purpose: "lab work",
    ti: "8:30:00 AM",
    to: "11:30:00 AM",
  },
  {
    key: "31",
    id: "31",
    date: "11-19-24",
    name: "Grace Nguyen",
    gender: "female",
    yl: "1st year",
    course: "BSED major in Science",
    purpose: "study",
    ti: "10:00:00 AM",
    to: "1:00:00 PM",
  },
  {
    key: "32",
    id: "32",
    date: "11-20-24",
    name: "Isaac Diaz",
    gender: "male",
    yl: "3rd year",
    course: "Bachelor of Science in Secondary Education major in English ",
    purpose: "tutoring",
    ti: "2:15:00 PM",
    to: "5:15:00 PM",
  },
  {
    key: "33",
    id: "33",
    date: "11-21-24",
    name: "Chloe Russell",
    gender: "female",
    yl: "4th year",
    course: "Bachelor of Science in Tourism Management",
    purpose: "project work",
    ti: "9:30:00 AM",
    to: "12:30:00 PM",
  },
  {
    key: "34",
    id: "34",
    date: "11-22-24",
    name: "Sebastian Foster",
    gender: "male",
    yl: "2nd year",
    course: "Bachelor of Science in Agriculture",
    purpose: "borrow book",
    ti: "11:00:00 AM",
    to: "2:00:00 PM",
  },
  {
    key: "35",
    id: "35",
    date: "11-23-24",
    name: "Sofia Simmons",
    gender: "female",
    yl: "1st year",
    course: "Bachelor of Science in Elementary Education",
    purpose: "computer lab",
    ti: "8:45:00 AM",
    to: "11:45:00 AM",
  },
  {
    key: "36",
    id: "36",
    date: "11-24-24",
    name: "Dylan Reed",
    gender: "male",
    yl: "3rd year",
    course: "Bachelor of Science in Information Technology",
    purpose: "research",
    ti: "1:30:00 PM",
    to: "4:30:00 PM",
  },
  {
    key: "37",
    id: "37",
    date: "11-25-24",
    name: "Zoey Cook",
    gender: "female",
    yl: "4th year",
    course: "Bachelor of Science in Hospitality Management",
    purpose: "thesis research",
    ti: "2:00:00 PM",
    to: "5:00:00 PM",
  },
  {
    key: "38",
    id: "38",
    date: "11-26-24",
    name: "Matthew Bell",
    gender: "male",
    yl: "2nd year",
    course: "Bachelor of Science in Secondary Education major in English",
    purpose: "group study",
    ti: "10:00:00 AM",
    to: "1:00:00 PM",
  },
  {
    key: "39",
    id: "39",
    date: "11-27-24",
    name: "Nora Coleman",
    gender: "female",
    yl: "1st year",
    course: "Bachelor of Science in Secondary Education major in Mathematics",
    purpose: "class project",
    ti: "9:00:00 AM",
    to: "12:00:00 PM",
  },
  {
    key: "40",
    id: "40",
    date: "11-28-24",
    name: "Logan Perry",
    gender: "male",
    yl: "3rd year",
    course:
      "Bachelor of Science in Industrial Technology major in Architecture",
    purpose: "consultation",
    ti: "1:15:00 PM",
    to: "4:15:00 PM",
  },
  {
    key: "41",
    id: "41",
    date: "11-29-24",
    name: "Layla Howard",
    gender: "female",
    yl: "4th year",
    course: "Bachelor of Science in Industrial Technology major in Automotive",
    purpose: "library work",
    ti: "11:00:00 AM",
    to: "2:00:00 PM",
  },
  {
    key: "42",
    id: "42",
    date: "11-30-24",
    name: "Julian Flores",
    gender: "male",
    yl: "2nd year",
    course: "Bachelor of Science in Industrial Technology major in Electronics",
    purpose: "study",
    ti: "10:15:00 AM",
    to: "1:15:00 PM",
  },
  {
    key: "43",
    id: "43",
    date: "12-01-24",
    name: "Lillian Bryant",
    gender: "female",
    yl: "1st year",
    course: "Bachelor of Science in Secondary Education major in Science",
    purpose: "library",
    ti: "1:00:00 PM",
    to: "4:00:00 PM",
  },
];

//////////////////////////////////////////////////////////
export const genders = [
  { key: "male", label: "Male" },
  { key: "female", label: "Female" },
];

export const yearlevels = [
  { key: "1", label: "1st Year" },
  { key: "2", label: "2nd Year" },
  { key: "3", label: "3rd Year" },
  { key: "4", label: "4th Year" },
];

export const courses = [
  { key: "ict", label: "Bachelor of Science in Information Technology" },
  { key: "hm", label: "Bachelor of Science in HM" },
  {
    key: "educS",
    label: "Bachelor of Science in Secondary Education major in Science",
  },
  {
    key: "educM",
    label: "Bachelor of Science in Secondary Education major in Mathematics",
  },
  {
    key: "educE",
    label: "Bachelor of Science in Secondary Education major in English",
  },
  { key: "agri", label: "Bachelor of Science in Agriculture" },
];

/////////////////////////////////////////////////////
export const animals = [
  { label: "NAME", value: "name", description: "" },
  { label: "GENDER", value: "gender", description: "" },
  { label: "YEAR LEVEL", value: "yl", description: "" },
  { label: "COURSE", value: "course", description: "" },
  { label: "PURPOSE", value: "purpose", description: "" },
];
